/**  
 * This program prints out a 3N+1 sequence starting from a positive 
 * integer specified by the user.  It also counts the number of 
 * terms in the sequence, and prints out that number.
 */
import java.util.Scanner;

public class PengEthanThreeN1 {

    public static void main(String[] args) {                

        int n;       // for computing terms in the sequence
        int counter = 0; // for counting the terms
        Scanner scanner = new Scanner(System.in);
        System.out.print("Starting point for sequence: ");
        int input = Integer.parseInt(scanner.nextLine());
        int countNum = 1;
        int max = 0;
        int maxCount = 0;
        while (countNum <= input) {
            n = countNum;
            counter = 0;
            while(n > 1) {
            	if(n % 2 == 0) { // even
            		n = n / 2;
            	}
            	else { // odd
            		n = 3*n + 1;
            	}
            	counter++;
            }
            if (counter > maxCount) {
                max = countNum;
                maxCount = counter;
            }
            countNum++;
        }

        System.out.println("The longest sequence possible from 1 - " + input + " generated by number " + max + " Length of sequence: " + maxCount);
    }  // end of main()

}  // end of class ThreeN1
